### ISSUE TITLE
Create baseline

### ISSUE THREAD

**Issue by yota-p** [yota-p/kaggle_jane-street-market-prediction#17]
## Description
Currently my model (ex004) doesn't reproduce the results on original notebook. 
There seems to be some bugs in my code. 

## Goal
Simple model with CV

## Impact
For baseline to compare with, in future trainings. 

## Reference
None

## Additional
None

## Tasks
- [ ] Reproduce [Market Prediction: XGBoost with GPU (Fit in 1min)](https://www.kaggle.com/hamditarek/market-prediction-xgboost-with-gpu-fit-in-1min?scriptVersionId=48127254)
- [ ] Implement CV based on [Coming soon...]()
- [ ] Run on Kaggle, submit
