### ISSUE TITLE
Minimalize feature engineering in training script

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_jane-street-market-prediction#27]
## Description
Currently input data contains index, feature & target. 
When trying to input multiple data, this causes a duplicated target columns. 

## Goal
- Calculate target column in FE
- Specify feature, target separately in configuration file
- Read specified file only in main module

## Impact
Capable of multiple feature input

## Reference
None

## Additional
Feature used for training will be equal to input features

## Tasks
- [x] Calculate target column in FE
- [x] Specify feature, target separately in configuration file
- [x] Read specified file only in main module
